# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.IntegerField(choices=[(1, '1 core'), (8, '8 cores'), (12, '12 cores')])),
                ('memory_size', models.IntegerField(choices=[(8, '8'), (12, '12')])),
                ('disk_size', models.IntegerField(choices=[(100, '100'), (200, '200')])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
