# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vmsareus.vmleases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.IntegerField()),
                ('memory_size', models.IntegerField()),
                ('host_os', models.CharField(default='ubumini', max_length=32)),
                ('vm_state', models.CharField(choices=[('q', 'queued'), ('c', 'creating'), ('r', 'running'), ('a', 'aborted')], default='q', max_length=1)),
                ('vm_name', models.CharField(default='', max_length=64)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_date', models.DateTimeField(default=vmsareus.vmleases.models.get_deadline)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
