# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='branch_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
