# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='disk_size',
            field=models.IntegerField(choices=[(100, '100 Gigabytes'), (200, '200 Gigabytes')]),
        ),
        migrations.AlterField(
            model_name='vm',
            name='memory_size',
            field=models.IntegerField(choices=[(8, '8 Gigabytes'), (12, '12 Gigabytes')]),
        ),
    ]
