# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0002_auto_20170728_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='disk_size',
        ),
    ]
