# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0002_vm_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='core_count',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='memory_size',
        ),
        migrations.AlterField(
            model_name='vm',
            name='vm_state',
            field=models.CharField(choices=[('q', 'queued'), ('c', 'creating'), ('p', 'prepping'), ('b', 'building'), ('r', 'running'), ('a', 'aborted')], default='q', max_length=1),
        ),
    ]
