# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0003_auto_20170922_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='starting_password',
            field=models.CharField(default=b'', max_length=128),
        ),
        migrations.AddField(
            model_name='vm',
            name='stash_key_id',
            field=models.IntegerField(default=0),
        ),
    ]
