# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import vmsareus.vmleases.models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0003_remove_vm_disk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='expires_date',
            field=models.DateTimeField(default=vmsareus.vmleases.models.get_deadline),
        ),
        migrations.AddField(
            model_name='vm',
            name='host_os',
            field=models.CharField(choices=[('ubumini', 'Ubuntu mini image'), ('win10dev', 'Windows 10 developer image')], default='ubumini', max_length=32),
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_state',
            field=models.CharField(choices=[('q', 'queued'), ('c', 'creating'), ('r', 'running'), ('a', 'aborted')], default='q', max_length=1),
        ),
        migrations.AlterField(
            model_name='vm',
            name='core_count',
            field=models.IntegerField(choices=[(1, '1 core'), (12, '12 cores')]),
        ),
        migrations.AlterField(
            model_name='vm',
            name='memory_size',
            field=models.IntegerField(choices=[(4, '4 Gigabytes'), (16, '32 Gigabytes')]),
        ),
    ]
