# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-28 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0004_auto_20170927_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='host_template',
            field=models.CharField(default=b'win10pe-vmsareus', max_length=128),
        ),
        migrations.AlterField(
            model_name='vm',
            name='host_os',
            field=models.CharField(default=b'Windows 10 latest/patched', max_length=64),
        ),
    ]
