# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0004_auto_20170817_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='vm_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
