# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0005_vm_vm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='', max_length=128)),
                ('display_name', models.CharField(default='', max_length=256)),
                ('display_icon', models.IntegerField(choices=[(1, 'none'), (2, 'windows 10 ssh')])),
                ('init_type', models.IntegerField(choices=[(1, 'none'), (2, 'windows 10 ssh')])),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vm',
            name='core_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vm',
            name='host_os',
            field=models.CharField(default='ubumini', max_length=32),
        ),
        migrations.AlterField(
            model_name='vm',
            name='memory_size',
            field=models.IntegerField(),
        ),
    ]
