# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0006_auto_20170913_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CPUOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hostos',
            name='display_name',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='cpuoptions',
            name='os_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmleases.HostOS'),
        ),
        migrations.AddField(
            model_name='coreoptions',
            name='os_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmleases.HostOS'),
        ),
    ]
