# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0007_auto_20170913_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemoryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='coreoptions',
            name='os_owner',
        ),
        migrations.RemoveField(
            model_name='cpuoptions',
            name='os_owner',
        ),
        migrations.DeleteModel(
            name='CoreOptions',
        ),
        migrations.DeleteModel(
            name='CPUOptions',
        ),
        migrations.AddField(
            model_name='hostos',
            name='cpu_choices',
            field=models.ManyToManyField(to='vmleases.CPUOption'),
        ),
        migrations.AddField(
            model_name='hostos',
            name='mem_choices',
            field=models.ManyToManyField(to='vmleases.MemoryOption'),
        ),
    ]
