# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0009_auto_20170913_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuoption',
            name='core_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='memoryoption',
            name='gigabyte_count',
            field=models.IntegerField(default=8),
        ),
    ]
