# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0010_auto_20170913_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostOS',
            new_name='HostOsOption',
        ),
    ]
