# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmleases', '0011_auto_20170913_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostosoption',
            name='cpu_choices',
        ),
        migrations.RemoveField(
            model_name='hostosoption',
            name='mem_choices',
        ),
    ]
